### ISSUE TITLE
Not all parameters are exposed to configure a postgresql datasource

### ISSUE THREAD

**Issue by MrLuje** [nytm/go-grafana-api#28]
**Describe the bug**
I can't configure all parameters of the postgres grafana_data_source type
```
resource "grafana_data_source" "pgsqldatasource" {
  type = "postgres"
}
```

From [grafana's doc](https://grafana.com/docs/grafana/latest/features/datasources/postgres/#data-source-options), the following parameters don't seem to be configurable :
- SSL Mode
- Max open
- Max idle
- Max lifetime
- Version
- TimescaleDB

**Comment by mlclmj** [comment]
This isn't a library issue--this was added in January with #35, though it hasn't made it into the provider yet. This has been on my to-do list but I'll try to get to it 😄

**Comment by MrLuje** [comment]
Yeah, my bad, this should have been created in the provider's repo
Thanks for adding the parameters 👍
