### ISSUE TITLE
Support alerting API

### ISSUE THREAD

**Issue by mdb** [nytm/go-grafana-api#54]
**Is your feature request related to a problem?**
As a user, it would be helpful if `go-grafana-api` supported the [Grafana alerting API](https://grafana.com/docs/grafana/latest/http_api/alerting/).

**Describe the solution you'd like**
I would like a collection of `go-grafana-api` methods supporting the alerting API:
* `Alerts`
* `Alert`
* `PauseAlert`
* `PauseAllAlerts`

**Additional context**
https://grafana.com/docs/grafana/latest/http_api/alerting/

**Comment by tonglil** [comment]
Closed by #55
